### ISSUE TITLE
Observation history API

### ISSUE THREAD

**Issue by hluker** [akrherz/iem-web-services#9]
Adding this to the wish list: https://mesonet.agron.iastate.edu/sites/obhistory.php?station=IOW&network=IA_ASOS

Basically the same as the current-currents API, but with an option to return x number of observations for a site (or between a set of dates, I suppose.)

**Comment by grguthrie** [comment]
Nice - is this same data available in machine readable (v.s. web page) format? json, xml, ...?

**Comment by akrherz** [comment]
I have something live now and would like your testing / feedback.  I am sure there are some bugs with this and I am currently rewritting an IEM website app to dogfood this service, so I suspect I'll see troubles there too.

[obhistory endpoint](https://mesonet.agron.iastate.edu/api/1/docs#/default/service_obhistory__fmt__get)

Will leave this issue open until you folks are happy with it.

**Comment by akrherz** [comment]
@hluker Thanks for the feedback, to address your items.

> Network specific variables

For RWIS, indeed, only the atmospherics are being returned.  Added #29.  For ISUSM, added #30

> Can we control the number of hours returned.

At present, I am only keen on having this service return one local day's worth of data.  At a future date, I may have a different service to return shorter and longer periods of archive data.

> The `?full=` setting is not working.

I am unsure of how you are using it within the context.  This setting only controls the variable domain returned.  Since the OpenAPI returns a potential schema, I wanted to provide an option to ensure the full schema was returned no matter which network was queried.

I'm gonna close this issue for now and we can iterate and only other issues for individual problems found.
